# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestLSTM' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestLSTM
  pod 'onnxruntime-objc', '~> 1.16.0'
end
